version: "3.9"
services:
  nginx:
    build: ./nginx
    volumes:
      - ./public:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - web
    links:
      - web:web
  web:
    build: .
    expose:
      - 5000
    volumes:
      - ./src:/app
    depends_on: 
      - db
    environment:
      - FLASK_ENV=development
      - DB_USER=task
      - DB_PASSWORD=task
      - DB_HOST=db
      - DB_DATABASE=task
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task
      - MYSQL_USER=task
      - MYSQL_PASSWORD=task
  adminer:
    image: adminer
    ports:
      - 8081:8080